-- prompt-share: チャプロ代替プロンプト共有
-- Supabase kamiooya-qa に追加（users 既存テーブルを管理者判定に共用）
-- RLS ON / service_role のみ CRUD（kamiooya-qa-web と同流儀）

create table if not exists public.prompt_groups (
  id bigint primary key generated by default as identity,
  name text not null,
  slug text not null unique,
  description text not null default '',
  sort_order integer not null default 0,
  access_level text not null default 'public'
    check (access_level in ('public', 'member')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists prompt_groups_sort_idx
  on public.prompt_groups (sort_order, id);

create table if not exists public.prompts (
  id bigint primary key generated by default as identity,
  group_id bigint references public.prompt_groups(id) on delete set null,
  title text not null,
  description text not null default '',
  template text not null default '',
  variables jsonb not null default '[]'::jsonb,
  public_token text not null unique,
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  access_level text not null default 'public'
    check (access_level in ('public', 'member')),
  view_count bigint not null default 0,
  generate_count bigint not null default 0,
  copy_count bigint not null default 0,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists prompts_group_id_idx on public.prompts (group_id);
create index if not exists prompts_status_idx on public.prompts (status);
create index if not exists prompts_public_token_idx on public.prompts (public_token);
create index if not exists prompts_updated_at_idx on public.prompts (updated_at desc);

create table if not exists public.prompt_usage_events (
  id bigint primary key generated by default as identity,
  prompt_id bigint not null references public.prompts(id) on delete cascade,
  event_type text not null
    check (event_type in ('view', 'generate', 'copy', 'open_chatgpt', 'open_gemini', 'open_claude', 'open_aistudio')),
  created_at timestamptz not null default now()
);

create index if not exists prompt_usage_events_prompt_id_idx
  on public.prompt_usage_events (prompt_id, created_at desc);
create index if not exists prompt_usage_events_type_idx
  on public.prompt_usage_events (event_type, created_at desc);

alter table public.prompt_groups enable row level security;
alter table public.prompts enable row level security;
alter table public.prompt_usage_events enable row level security;

revoke all on table public.prompt_groups from anon, authenticated;
revoke all on table public.prompts from anon, authenticated;
revoke all on table public.prompt_usage_events from anon, authenticated;

grant all on table public.prompt_groups to service_role;
grant all on table public.prompts to service_role;
grant all on table public.prompt_usage_events to service_role;

grant usage, select on all sequences in schema public to service_role;
