-- KURASHIFT: ライフプラン時点版 + 財務実績の長期履歴
-- 用途: 過去時点の計画(.numbers)と Zaim 実績の付け合わせ・Jarvis相談の正本

-- ========== ライフプラン時点版（.numbers 1ファイル = 1版） ==========

create table if not exists public.kurashift_lifeplan_versions (
  id uuid primary key default gen_random_uuid(),
  version_key text not null unique,
  as_of date not null,
  source_path text not null,
  source_filename text not null,
  label text,
  is_canonical boolean not null default false,
  file_mtime timestamptz,
  file_size_bytes bigint,
  extract_status text not null default 'pending'
    check (extract_status in ('pending', 'partial', 'ok', 'failed', 'skipped')),
  extract_notes text,
  sheet_names jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists kurashift_lifeplan_versions_as_of_idx
  on public.kurashift_lifeplan_versions (as_of desc);

-- 正規化した月次予算行（計画）。版×年×月×カテゴリ
create table if not exists public.kurashift_lifeplan_budget_rows (
  id bigint generated by default as identity primary key,
  version_id uuid not null references public.kurashift_lifeplan_versions(id) on delete cascade,
  plan_year int not null,
  month int not null check (month between 1 and 12),
  numbers_category text not null default '',
  category_key text,
  amount_yen numeric not null default 0,
  series text not null default 'plan'
    check (series in ('plan', 'actual_col', 'unknown')),
  created_at timestamptz not null default now(),
  unique (version_id, plan_year, month, numbers_category, series)
);

create index if not exists kurashift_lifeplan_budget_rows_year_idx
  on public.kurashift_lifeplan_budget_rows (plan_year, month);

-- シート生ダンプ（列レイアウトが古い版でも参照可能）
create table if not exists public.kurashift_lifeplan_sheet_dumps (
  id uuid primary key default gen_random_uuid(),
  version_id uuid not null references public.kurashift_lifeplan_versions(id) on delete cascade,
  sheet_name text not null,
  table_name text not null default '表1',
  row_count int,
  col_count int,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (version_id, sheet_name, table_name)
);

-- ========== 財務実績（Zaim 年度 CSV） ==========

create table if not exists public.kurashift_finance_sources (
  id uuid primary key default gen_random_uuid(),
  source_key text not null unique,
  fiscal_year int not null,
  kind text not null default 'zaim_raw'
    check (kind in ('zaim_raw', 'zaim_lifeplan_summary')),
  source_path text not null,
  row_count int not null default 0,
  checksum text,
  file_mtime timestamptz,
  imported_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create index if not exists kurashift_finance_sources_year_idx
  on public.kurashift_finance_sources (fiscal_year desc);

create table if not exists public.kurashift_finance_transactions (
  id bigint generated by default as identity primary key,
  source_id uuid not null references public.kurashift_finance_sources(id) on delete cascade,
  fiscal_year int not null,
  row_index int not null,
  txn_date date,
  method text,
  category text,
  subcategory text,
  description text,
  memo text,
  from_account text,
  to_account text,
  income_jpy numeric not null default 0,
  expense_jpy numeric not null default 0,
  balance_jpy numeric,
  currency text,
  aggregation text,
  entity text,
  kind text,
  created_at timestamptz not null default now(),
  unique (source_id, row_index)
);

create index if not exists kurashift_finance_txn_date_idx
  on public.kurashift_finance_transactions (txn_date desc);
create index if not exists kurashift_finance_txn_year_cat_idx
  on public.kurashift_finance_transactions (fiscal_year, category);

-- ライフプラン用サマリー（年×カテゴリの収入/支出）
create table if not exists public.kurashift_finance_category_year (
  id bigint generated by default as identity primary key,
  source_id uuid not null references public.kurashift_finance_sources(id) on delete cascade,
  fiscal_year int not null,
  category text not null,
  income_jpy numeric not null default 0,
  expense_jpy numeric not null default 0,
  net_jpy numeric not null default 0,
  abg text,
  created_at timestamptz not null default now(),
  unique (source_id, category)
);

create index if not exists kurashift_finance_category_year_idx
  on public.kurashift_finance_category_year (fiscal_year, abg);

do $$
declare
  t text;
begin
  foreach t in array array[
    'kurashift_lifeplan_versions',
    'kurashift_lifeplan_budget_rows',
    'kurashift_lifeplan_sheet_dumps',
    'kurashift_finance_sources',
    'kurashift_finance_transactions',
    'kurashift_finance_category_year'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I_auth_all on public.%I', t, t);
    execute format(
      'create policy %I_auth_all on public.%I for all to authenticated using (true) with check (true)',
      t, t
    );
  end loop;
end $$;
