-- KURASHIFT Sprint 2: 買い進めプラン版管理 + 千三つファネル案件 + 運営経緯

-- ========== 買い進め Excel 時点版 ==========

create table if not exists public.kurashift_buy_plan_versions (
  id uuid primary key default gen_random_uuid(),
  version_key text not null unique,
  as_of date not null,
  source_path text not null,
  source_filename text not null,
  label text,
  is_canonical boolean not null default false,
  file_mtime timestamptz,
  file_size_bytes bigint,
  extract_status text not null default 'pending'
    check (extract_status in ('pending', 'partial', 'ok', 'failed', 'skipped')),
  extract_notes text,
  sheet_names jsonb not null default '[]'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists kurashift_buy_plan_versions_as_of_idx
  on public.kurashift_buy_plan_versions (as_of desc);

-- STEP3 の購入・売却・資金調達行
create table if not exists public.kurashift_buy_plan_events (
  id bigint generated by default as identity primary key,
  version_id uuid not null references public.kurashift_buy_plan_versions(id) on delete cascade,
  row_no int not null,
  action text,
  entity text,
  location text,
  structure text,
  built_year text,
  price_man numeric,
  yield_pct numeric,
  reno_man numeric,
  cost_man numeric,
  bank text,
  loan_man numeric,
  down_man numeric,
  rate_pct numeric,
  loan_years numeric,
  property_name text,
  sale_strategy text,
  event_date date,
  memo text,
  extras jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (version_id, row_no)
);

create index if not exists kurashift_buy_plan_events_action_idx
  on public.kurashift_buy_plan_events (action);

-- エリア条件・購入ルール（箇条書きを jsonb 化）
create table if not exists public.kurashift_buy_plan_criteria (
  id bigint generated by default as identity primary key,
  version_id uuid not null references public.kurashift_buy_plan_versions(id) on delete cascade,
  kind text not null check (kind in ('area', 'purchase_rule', 'other')),
  sort_order int not null default 0,
  payload jsonb not null default '{}'::jsonb,
  raw_text text,
  created_at timestamptz not null default now()
);

create index if not exists kurashift_buy_plan_criteria_version_idx
  on public.kurashift_buy_plan_criteria (version_id, kind);

-- プランニング制約（銀行×担保）
create table if not exists public.kurashift_buy_plan_constraints (
  id bigint generated by default as identity primary key,
  version_id uuid not null references public.kurashift_buy_plan_versions(id) on delete cascade,
  row_no int not null default 0,
  updated_on date,
  collateral_type text,
  guarantor text,
  lender text,
  limit_note text,
  attr_note text,
  rate_term text,
  prop_cond text,
  income_cond text,
  geo_cond text,
  extras jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (version_id, row_no)
);

-- 木村さんコメント等の自由記述シート
create table if not exists public.kurashift_buy_plan_notes (
  id uuid primary key default gen_random_uuid(),
  version_id uuid not null references public.kurashift_buy_plan_versions(id) on delete cascade,
  sheet_name text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (version_id, sheet_name)
);

-- ========== 千三つファネル（案件） ==========

create table if not exists public.kurashift_re_deals (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  status text not null default 'info'
    check (status in (
      'info', 'viewing', 'offer', 'loan', 'purchased', 'passed', 'archived'
    )),
  source text not null default 'manual'
    check (source in ('mail_admin', 'mail_estate', 'kenbiya', 'rakumachi', 'manual', 'other')),
  area text,
  structure text,
  price_man numeric,
  yield_pct numeric,
  match_score numeric,
  summary_json jsonb not null default '{}'::jsonb,
  advice_json jsonb not null default '{}'::jsonb,
  first_seen_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists kurashift_re_deals_status_idx
  on public.kurashift_re_deals (status, updated_at desc);

-- ========== 運営年次相談タイムライン ==========

create table if not exists public.kurashift_ops_consult_events (
  id uuid primary key default gen_random_uuid(),
  occurred_at timestamptz not null,
  channel text not null default 'yoritoori'
    check (channel in ('yoritoori', 'gmail_admin', 'gmail_estate', 'manual')),
  partner_folder text,
  subject text,
  snippet text,
  tags text[] not null default '{}',
  source_ref text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists kurashift_ops_consult_events_at_idx
  on public.kurashift_ops_consult_events (occurred_at desc);

-- RLS: service_role / dashboard anon は既存 kurashift_* と同様にアプリ側で制御
-- （ダッシュボードは authenticated + service_role。ここでは表作成のみ）
