-- Glucon report feature (activity / result reports for 神大家)

create table if not exists public.glucon_schedule (
  id bigint generated by default as identity primary key,
  glucon_date date not null unique,
  report_deadline date not null,
  title text not null default '',
  source text not null default 'scraped' check (source in ('scraped', 'estimated', 'manual')),
  comment_id text,
  updated_at timestamptz not null default now()
);

create index if not exists glucon_schedule_deadline_idx
  on public.glucon_schedule (report_deadline desc);

create table if not exists public.glucon_journal_days (
  recorded_at date primary key,
  excerpt text not null default '',
  keywords text[] not null default '{}',
  char_count integer not null default 0,
  synced_at timestamptz not null default now()
);

create index if not exists glucon_journal_days_synced_idx
  on public.glucon_journal_days (synced_at desc);

create table if not exists public.glucon_report_drafts (
  id uuid primary key default gen_random_uuid(),
  period_key text not null,
  kind text not null check (kind in ('activity', 'result')),
  glucon_date date,
  report_deadline date,
  title text not null default '',
  body text not null default '',
  status text not null default 'draft'
    check (status in ('draft', 'ready', 'queued', 'posted', 'failed', 'skipped')),
  examples jsonb not null default '[]'::jsonb,
  journal_day_count integer not null default 0,
  post_error text,
  posted_at timestamptz,
  westudy_comment_id text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (period_key, kind)
);

create index if not exists glucon_report_drafts_status_idx
  on public.glucon_report_drafts (status, updated_at desc);

alter table public.glucon_schedule enable row level security;
alter table public.glucon_journal_days enable row level security;
alter table public.glucon_report_drafts enable row level security;

drop policy if exists glucon_schedule_auth_all on public.glucon_schedule;
create policy glucon_schedule_auth_all on public.glucon_schedule
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists glucon_journal_days_auth_all on public.glucon_journal_days;
create policy glucon_journal_days_auth_all on public.glucon_journal_days
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists glucon_report_drafts_auth_all on public.glucon_report_drafts;
create policy glucon_report_drafts_auth_all on public.glucon_report_drafts
  for all to authenticated
  using (true)
  with check (true);
