-- KURASHIFT HQ: liquidity history, securities holdings, money ops
-- Project: jarvis-dashboard

create table if not exists public.liquidity_accounts (
  id text primary key,
  name text not null,
  kind text not null
    check (kind in ('bank', 'card', 'emoney', 'cash')),
  zaim_match text not null,
  active boolean not null default true,
  sort_order int not null default 100,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.liquidity_snapshots (
  id bigint generated by default as identity primary key,
  account_id text not null references public.liquidity_accounts(id) on delete cascade,
  as_of date not null,
  balance_jpy numeric not null,
  source text not null default 'zaim',
  note text,
  created_at timestamptz not null default now(),
  unique (account_id, as_of)
);

create index if not exists liquidity_snapshots_as_of_idx
  on public.liquidity_snapshots (as_of desc);

create table if not exists public.cashflow_week_summaries (
  week_start date primary key,
  income_jpy numeric,
  expense_jpy numeric,
  credit_spend_jpy numeric,
  note text,
  source text not null default 'zaim',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.securities_holdings (
  id bigint generated by default as identity primary key,
  account_id text not null references public.portfolio_accounts(id) on delete cascade,
  as_of date not null,
  value_jpy numeric,
  source text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (account_id, as_of)
);

create index if not exists securities_holdings_as_of_idx
  on public.securities_holdings (as_of desc);

-- kind は後続で card_settlement_buffer を追加
-- （20260814_kurashift_money_ops_card_settlement.sql）
create table if not exists public.kurashift_money_ops (
  id uuid primary key default gen_random_uuid(),
  kind text not null
    check (kind in (
      'bank_transfer', 'broker_transfer', 'securities_cash', 'insurance_alloc',
      'card_settlement_buffer'
    )),
  title text not null,
  rationale text not null default '',
  from_account text,
  to_account text,
  amount_jpy numeric,
  status text not null default 'draft'
    check (status in ('draft', 'consulting', 'approved', 'executing', 'done', 'cancelled')),
  assist_payload jsonb not null default '{}'::jsonb,
  consultation_id uuid references public.kurashift_consultations(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists kurashift_money_ops_status_created_idx
  on public.kurashift_money_ops (status, created_at desc);

insert into public.liquidity_accounts (id, name, kind, zaim_match, sort_order, notes) values
  ('smbc_kariya', '三井住友銀行 刈谷', 'bank', '三井住友銀行 刈谷', 10, '生活メイン'),
  ('sbinet_main', '住信SBIネット銀行', 'bank', '住信SBIネット銀行', 20, 'そなえ／振替'),
  ('sbinet_alt', '住信 SBI ネット銀行', 'bank', '住信 SBI ネット銀行', 21, '表記ゆれ別'),
  ('mufg_apart', 'MUFG(アパート経営)', 'bank', 'MUFG(アパート経営)', 30, '不動産関連'),
  ('mufg_toyoake', '三菱UFJ銀行 豊明', 'bank', '三菱UFJ銀行 豊明', 31, null),
  ('paypay_bank', 'PayPay銀行', 'bank', 'PayPay銀行', 40, null),
  ('tokai_roukin', '東海労金(生活こども)', 'bank', '東海労金', 50, null),
  ('shiga_kusatsu', '滋賀銀行 草津', 'bank', '滋賀銀行', 55, null),
  ('ogaki', '大垣共立銀行', 'bank', '大垣共立銀行', 60, null),
  ('meigin', '名古屋銀行', 'bank', '名古屋銀行', 65, null),
  ('kyoto_kariya', '京都銀行 刈谷', 'bank', '京都銀行', 70, null),
  ('wallet', 'お財布', 'cash', 'お財布', 80, null),
  ('olive_card', 'Olive / Vpass', 'card', 'Olive', 90, 'クレジット支出集計用'),
  ('amex', 'AMEX', 'card', 'AMEX', 91, 'クレジット支出集計用'),
  ('suica', 'Suica', 'emoney', 'Suica', 100, null)
on conflict (id) do nothing;

do $$
declare
  t text;
begin
  foreach t in array array[
    'liquidity_accounts', 'liquidity_snapshots', 'cashflow_week_summaries',
    'securities_holdings', 'kurashift_money_ops'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I_auth_all on public.%I', t, t);
    execute format(
      'create policy %I_auth_all on public.%I for all to authenticated using (true) with check (true)',
      t, t
    );
  end loop;
end $$;
