-- Trade Desk: 株自動売買（ペーパートレード）＋資産全体ビュー
-- 自分用 jarvis-dashboard プロジェクト。新規 PJ は作らない。

-- ========== 売買・学習ループ ==========

create table if not exists public.trade_instruments (
  symbol text primary key,
  ticker_jp text,
  name text not null,
  theme text not null default 'other',
  asset_class text not null default 'equity'
    check (asset_class in ('equity', 'etf', 'inverse_etf', 'index')),
  enabled boolean not null default true,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.trade_prices (
  id bigint generated by default as identity primary key,
  symbol text not null references public.trade_instruments(symbol) on delete cascade,
  trade_date date not null,
  open numeric,
  high numeric,
  low numeric,
  close numeric,
  volume bigint,
  source text not null default 'yahoo',
  unique (symbol, trade_date)
);

create index if not exists trade_prices_symbol_date_idx
  on public.trade_prices (symbol, trade_date desc);

create table if not exists public.trade_signals (
  id uuid primary key default gen_random_uuid(),
  signal_date date not null,
  symbol text not null,
  side text not null
    check (side in ('buy', 'sell', 'hold', 'inverse_buy', 'inverse_sell')),
  score numeric,
  reason text not null,
  regime text,
  status text not null default 'paper'
    check (status in (
      'paper', 'pending_approval', 'approved', 'rejected',
      'executed', 'skipped', 'cancelled'
    )),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trade_signals_date_idx
  on public.trade_signals (signal_date desc, symbol);

create table if not exists public.trade_orders (
  id uuid primary key default gen_random_uuid(),
  signal_id uuid references public.trade_signals(id) on delete set null,
  mode text not null default 'paper' check (mode in ('paper', 'live')),
  symbol text not null,
  side text not null,
  qty integer,
  limit_price numeric,
  filled_price numeric,
  filled_at timestamptz,
  status text not null default 'simulated',
  broker text not null default 'paper',
  broker_order_id text,
  reason text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trade_orders_mode_status_idx
  on public.trade_orders (mode, status, created_at desc);

create table if not exists public.trade_positions (
  id uuid primary key default gen_random_uuid(),
  mode text not null default 'paper' check (mode in ('paper', 'live')),
  symbol text not null,
  qty integer not null,
  avg_price numeric not null,
  opened_at date not null,
  closed_at date,
  status text not null default 'open' check (status in ('open', 'closed')),
  stop_price numeric,
  take_profit_price numeric,
  realized_pnl numeric,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists trade_positions_mode_status_idx
  on public.trade_positions (mode, status);

create table if not exists public.trade_daily_pnl (
  trade_date date not null,
  mode text not null default 'paper' check (mode in ('paper', 'live')),
  equity numeric not null,
  cash numeric not null,
  unrealized_pnl numeric,
  realized_pnl_day numeric,
  drawdown_pct numeric,
  tranche integer,
  kill_switch boolean not null default false,
  payload jsonb not null default '{}'::jsonb,
  primary key (trade_date, mode)
);

create table if not exists public.trade_risk_state (
  id text primary key,
  tranche integer not null default 1,
  capital_jpy numeric not null default 100000,
  peak_equity numeric,
  current_equity numeric,
  drawdown_pct numeric,
  kill_switch boolean not null default false,
  kill_reason text,
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_params (
  id text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now()
);

create table if not exists public.trade_reviews (
  id uuid primary key default gen_random_uuid(),
  week_start date not null,
  summary text,
  user_comment text,
  jarvis_proposal text,
  status text not null default 'open' check (status in ('open', 'applied', 'dismissed')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.trade_research (
  id uuid primary key default gen_random_uuid(),
  source text not null,
  topic text,
  fetched_at timestamptz not null default now(),
  summary text,
  url text,
  payload jsonb not null default '{}'::jsonb
);

-- ========== 資産全体ビュー ==========

create table if not exists public.portfolio_accounts (
  id text primary key,
  name text not null,
  kind text not null,
  institution text,
  currency text not null default 'JPY',
  ingest text not null default 'monthly_form',
  notes text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.portfolio_snapshots (
  id bigint generated by default as identity primary key,
  account_id text not null references public.portfolio_accounts(id) on delete cascade,
  as_of date not null,
  value_jpy numeric not null,
  cost_jpy numeric,
  source text,
  note text,
  created_at timestamptz not null default now(),
  unique (account_id, as_of)
);

create table if not exists public.portfolio_cashflows (
  id uuid primary key default gen_random_uuid(),
  account_id text not null references public.portfolio_accounts(id) on delete cascade,
  flow_date date not null,
  kind text not null
    check (kind in ('contribution', 'withdrawal', 'living_draw', 'dividend', 'transfer_in', 'transfer_out')),
  amount_jpy numeric not null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists portfolio_cashflows_account_date_idx
  on public.portfolio_cashflows (account_id, flow_date desc);

create table if not exists public.advisor_notes (
  id uuid primary key default gen_random_uuid(),
  advisor text not null default 'ishikawa',
  note_date date not null default current_date,
  body text not null,
  related_accounts text[],
  created_at timestamptz not null default now()
);

-- RLS（既存テーブルと同じ: authenticated 全許可。service_role はバイパス）
do $$
declare
  t text;
begin
  foreach t in array array[
    'trade_instruments', 'trade_prices', 'trade_signals', 'trade_orders',
    'trade_positions', 'trade_daily_pnl', 'trade_risk_state', 'trade_params',
    'trade_reviews', 'trade_research', 'portfolio_accounts', 'portfolio_snapshots',
    'portfolio_cashflows', 'advisor_notes'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I_auth_all on public.%I', t, t);
    execute format(
      'create policy %I_auth_all on public.%I for all to authenticated using (true) with check (true)',
      t, t
    );
  end loop;
end $$;

-- シード: リスク状態・戦略パラメータ
insert into public.trade_risk_state (id, tranche, capital_jpy, peak_equity, current_equity, drawdown_pct, kill_switch)
values
  ('paper', 1, 100000, 100000, 100000, 0, false),
  ('live', 1, 100000, 100000, 100000, 0, false)
on conflict (id) do nothing;

insert into public.trade_params (id, value)
values (
  'strategy_v1',
  '{
    "sma_fast": 20,
    "sma_slow": 60,
    "rsi_period": 14,
    "style": "mean_reversion_scale",
    "rsi_buy_low": 25,
    "rsi_buy_high": 48,
    "pullback_pct": 0.02,
    "drop_min_pct": 0.08,
    "drop_max_pct": 0.22,
    "rebound_min_signs": 2,
    "scale_fracs": [0.25, 0.35, 0.40],
    "confirm_gain_pct": 0.02,
    "convince_rsi": 50,
    "partial_exit_frac": 0.5,
    "rhythm_fail_pct": 0.03,
    "mean_target_band": 0.015,
    "take_profit_pct": 0.12,
    "stop_loss_pct": 0.08,
    "max_hold_days": 20,
    "max_positions": 4,
    "per_name_pct": 0.20,
    "weekly_loss_halt_pct": 0.05,
    "downgrade_pct": 0.10,
    "halt_pct": 0.20,
    "promote_weeks": 8,
    "promote_max_dd_pct": 0.08
  }'::jsonb
)
on conflict (id) do nothing;

insert into public.portfolio_accounts (id, name, kind, institution, ingest, notes)
values
  ('sony_life', 'ソニー生命（変額）', 'insurance_sony', 'ソニー生命', 'monthly_form', 'IFA石川さん。世界株・日本株・債券の組合せ'),
  ('axa_life', 'アクサ生命（積立）', 'insurance_axa', 'アクサ生命', 'monthly_form', '毎月定額積立'),
  ('sbi_index', 'SBI インデックス投資', 'index_sbi', 'SBI証券', 'zaim', '投信積立・自動投資設定'),
  ('mhi_stock', '三菱重工 持株会', 'employee_stock', '野村マイ・ターゲット', 'zaim', '継続買付。取得単価と現在値で効率を見る'),
  ('akatsuki_bond', 'あかつき証券 債券', 'bond_akatsuki', 'あかつき証券', 'akatsuki_script', 'IFA石川さん。利回りから生活費取り出し'),
  ('tachibana_trade', '立花証券 自動売買', 'trade_tachibana', '立花証券e支店', 'auto_trade', '現物スイング。Tranche制')
on conflict (id) do nothing;
