-- Quiet Edge: persisted reviews (ingest / monthly)
create table if not exists public.vital_quiet_reviews (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('ingest', 'monthly')),
  period_key text not null,
  title text not null default '',
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists vital_quiet_reviews_kind_created_idx
  on public.vital_quiet_reviews (kind, created_at desc);

create index if not exists vital_quiet_reviews_period_idx
  on public.vital_quiet_reviews (kind, period_key, created_at desc);

alter table public.vital_quiet_reviews enable row level security;

drop policy if exists vital_quiet_reviews_auth_all on public.vital_quiet_reviews;
create policy vital_quiet_reviews_auth_all on public.vital_quiet_reviews
  for all to authenticated
  using (true)
  with check (true);
