-- Quiet Edge Phase 3: journal join + context notes

create table if not exists public.vital_journal_daily (
  recorded_at date primary key,
  excerpt text not null default '',
  char_count integer not null default 0,
  source text not null default 'obsidian_star_journal',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists vital_journal_daily_updated_idx
  on public.vital_journal_daily (updated_at desc);

create table if not exists public.vital_context_notes (
  id bigint generated by default as identity primary key,
  recorded_at date not null,
  trigger text not null default 'manual',
  prompt text not null default '',
  answer text not null,
  source text not null default 'user_reply',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists vital_context_notes_recorded_idx
  on public.vital_context_notes (recorded_at desc, created_at desc);

alter table public.vital_journal_daily enable row level security;
alter table public.vital_context_notes enable row level security;

drop policy if exists vital_journal_daily_auth_all on public.vital_journal_daily;
create policy vital_journal_daily_auth_all on public.vital_journal_daily
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists vital_context_notes_auth_all on public.vital_context_notes;
create policy vital_context_notes_auth_all on public.vital_context_notes
  for all to authenticated
  using (true)
  with check (true);
