-- Quiet Edge Phase 2: vital_daily (Health metrics)

create table if not exists public.vital_daily (
  id bigint generated by default as identity primary key,
  recorded_at date not null,
  metric text not null,
  value double precision not null,
  unit text,
  source text not null default 'health_unknown',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (recorded_at, metric, source)
);

create index if not exists vital_daily_recorded_idx
  on public.vital_daily (recorded_at desc);

create index if not exists vital_daily_metric_idx
  on public.vital_daily (metric, recorded_at desc);

alter table public.vital_daily enable row level security;

drop policy if exists vital_daily_auth_all on public.vital_daily;
create policy vital_daily_auth_all on public.vital_daily
  for all to authenticated
  using (true)
  with check (true);
