-- Jarvis 自分用ダッシュボード（jarvis-dashboard）
-- 運営提供用 kamiooya-qa とは分離。引き渡さない。
-- 適用: Supabase MCP apply_migration / SQL Editor

-- triage_items: 夜間トリアージ queue 相当
-- status: pending(未読) / sent(送信済み) / skipped / snoozed(後で) / done(旧・互換)
-- payload 例: draft_gemini, draft_cursor, sent_at, gmail_sent_id,
--   yoritoori_appended, web_draft_saved_at
create table if not exists public.triage_items (
  id text primary key,
  lane text not null default 'partner',
  kind text not null default 'mail',
  status text not null default 'pending',
  partner text,
  folder text,
  subject text,
  received_at text,
  summary text,
  draft_text text,
  original_body text,
  priority text,
  channel text,
  account text,
  gmail_thread_id text,
  gmail_message_id text,
  from_email text,
  payload jsonb not null default '{}'::jsonb,
  seq integer,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists triage_items_lane_status_idx
  on public.triage_items (lane, status);
create index if not exists triage_items_updated_at_idx
  on public.triage_items (updated_at desc);

-- watch_status: 状況ウォッチ判定スナップ
create table if not exists public.watch_status (
  id text primary key,
  title text not null,
  category text,
  level text not null default 'info',
  summary text,
  detail text,
  source text,
  cursor_prompt text,
  status text not null default 'active' check (status in ('active', 'archived')),
  archived_at timestamptz,
  checked_at timestamptz,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists watch_status_level_idx
  on public.watch_status (status, level);

-- cards: 全レーン共通カード（神大家・物件・戸建て・AI/Raimo など）
create table if not exists public.cards (
  id text primary key,
  lane text not null,
  kind text not null default 'note',
  title text not null,
  summary text,
  status text not null default 'active' check (status in ('active', 'archived', 'promoted')),
  source_path text,
  cursor_prompt text,
  payload jsonb not null default '{}'::jsonb,
  archived_at timestamptz,
  sort_key text,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists cards_lane_status_idx
  on public.cards (lane, status);

-- card_comments: 処置候補カードへのユーザー↔Jarvis コメント
create table if not exists public.card_comments (
  id bigint generated by default as identity primary key,
  card_id text not null references public.cards(id) on delete cascade,
  role text not null check (role in ('user', 'jarvis')),
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists card_comments_card_id_idx
  on public.card_comments (card_id, created_at);

-- lane_action_log: ダッシュボード操作 → Mac で Jarvis処置ログ MD へ flush
create table if not exists public.lane_action_log (
  id bigserial primary key,
  lane text not null,
  event text not null,
  body text not null,
  card_id text,
  created_at timestamptz not null default now(),
  flushed_at timestamptz
);

create index if not exists lane_action_log_flush_idx
  on public.lane_action_log (flushed_at, created_at);

create index if not exists lane_action_log_lane_idx
  on public.lane_action_log (lane, created_at desc);

-- metrics: モチベーション数値・財務時系列
create table if not exists public.metrics (
  id bigint generated by default as identity primary key,
  metric text not null,
  value double precision not null,
  unit text,
  entity text not null default 'all',
  recorded_at date not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (metric, entity, recorded_at)
);

create index if not exists metrics_metric_recorded_idx
  on public.metrics (metric, recorded_at desc);

-- sync_meta: 最終 push 時刻など
create table if not exists public.sync_meta (
  key text primary key,
  value text,
  updated_at timestamptz not null default now()
);

-- subscription_services: 課金／SaaS 一覧（config/subscriptions.yaml から push）
create table if not exists public.subscription_services (
  id text primary key,
  name text not null,
  category text not null default 'lifestyle',
  status text not null default 'unknown',
  billing text not null default 'none',
  amount_yen double precision not null default 0,
  monthly_yen double precision not null default 0,
  next_bill text,
  watch boolean not null default false,
  watch_reason text,
  usage_note text,
  cancel_candidate boolean not null default false,
  billing_url text,
  note text,
  updated_at timestamptz not null default now()
);

create index if not exists subscription_services_category_idx
  on public.subscription_services (category);
create index if not exists subscription_services_watch_idx
  on public.subscription_services (watch)
  where watch = true;

-- watch_comments: 状況ウォッチへのユーザー↔Jarvis コメント
create table if not exists public.watch_comments (
  id bigint generated by default as identity primary key,
  watch_id text not null references public.watch_status(id) on delete cascade,
  role text not null check (role in ('user', 'jarvis')),
  body text not null,
  created_at timestamptz not null default now()
);

create index if not exists watch_comments_watch_id_idx
  on public.watch_comments (watch_id, created_at);

-- property_units: 物件号室の現況（家賃マップ／メール更新）
create table if not exists public.property_units (
  id text primary key,
  property_id text not null,
  property_name text not null,
  room text not null,
  status text not null default 'occupied'
    check (status in ('occupied', 'vacant')),
  rent double precision,
  note text,
  source text not null default 'excel',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (property_id, room)
);

create index if not exists property_units_property_idx
  on public.property_units (property_id, room);

-- property_occupancy_events: 空室／入居履歴
create table if not exists public.property_occupancy_events (
  id bigint generated by default as identity primary key,
  occurred_on date not null,
  event_type text not null check (event_type in ('vacant', 'occupied')),
  property_id text not null,
  property_name text,
  room text not null,
  source text not null default 'mail',
  ref text,
  note text,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists property_occupancy_events_occurred_idx
  on public.property_occupancy_events (occurred_on desc, property_id, room);

-- vital_snore_daily: AutoSnore いびき日次（Quiet Edge）
-- recorded_at = 起床側の暦日。score=イビガースコア、count=検出回数
create table if not exists public.vital_snore_daily (
  recorded_at date primary key,
  score double precision not null,
  count integer,
  event text not null default '通常日',
  sleep_time text,
  memo text,
  source text not null default 'autosnore_ocr',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists vital_snore_daily_recorded_idx
  on public.vital_snore_daily (recorded_at desc);

-- vital_treatment_events: いびきレーザー治療スケジュール（総回数の目安は最大9回）
-- status: done / scheduled / planned（枠・日程未定） / cancelled
-- 更新本線: Jarvis チャット → scripts/jarvis_quiet_edge_treatment.py（アプリUIは作らない）
create table if not exists public.vital_treatment_events (
  id bigint generated by default as identity primary key,
  session_no integer not null unique,
  scheduled_at timestamptz,
  label text not null,
  status text not null default 'scheduled'
    check (status in ('done', 'scheduled', 'cancelled', 'planned')),
  note text,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists vital_treatment_events_scheduled_idx
  on public.vital_treatment_events (scheduled_at);

-- vital_daily: Apple Health / OraMemo / Watch 日次指標（Quiet Edge Phase 2）
-- metric 例: sleep_hours, spo2, respiratory_rate, hrv, resting_hr
create table if not exists public.vital_daily (
  id bigint generated by default as identity primary key,
  recorded_at date not null,
  metric text not null,
  value double precision not null,
  unit text,
  source text not null default 'health_unknown',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (recorded_at, metric, source)
);

create index if not exists vital_daily_recorded_idx
  on public.vital_daily (recorded_at desc);

create index if not exists vital_daily_metric_idx
  on public.vital_daily (metric, recorded_at desc);

-- vital_journal_daily: Obsidian ★Journal 抜粋（Quiet Edge Phase 3）
create table if not exists public.vital_journal_daily (
  recorded_at date primary key,
  excerpt text not null default '',
  char_count integer not null default 0,
  sleep_signal text not null default '',
  sleep_tags text[] not null default '{}'::text[],
  source text not null default 'obsidian_star_journal',
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists vital_journal_daily_updated_idx
  on public.vital_journal_daily (updated_at desc);

-- vital_context_notes: 「何がありましたか？」の補完メモ
create table if not exists public.vital_context_notes (
  id bigint generated by default as identity primary key,
  recorded_at date not null,
  trigger text not null default 'manual',
  prompt text not null default '',
  answer text not null,
  source text not null default 'user_reply',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists vital_context_notes_recorded_idx
  on public.vital_context_notes (recorded_at desc, created_at desc);

-- vital_quiet_reviews: 取込直後レビュー / 月次レビュー
create table if not exists public.vital_quiet_reviews (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('ingest', 'monthly')),
  period_key text not null,
  title text not null default '',
  body text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists vital_quiet_reviews_kind_created_idx
  on public.vital_quiet_reviews (kind, created_at desc);

create index if not exists vital_quiet_reviews_period_idx
  on public.vital_quiet_reviews (kind, period_key, created_at desc);

-- glucon_schedule: グルコン開催日・提出期限（開催日−10日）
create table if not exists public.glucon_schedule (
  id bigint generated by default as identity primary key,
  glucon_date date not null unique,
  report_deadline date not null,
  title text not null default '',
  source text not null default 'scraped' check (source in ('scraped', 'estimated', 'manual')),
  comment_id text,
  updated_at timestamptz not null default now()
);

create index if not exists glucon_schedule_deadline_idx
  on public.glucon_schedule (report_deadline desc);

-- glucon_journal_days: Obsidian ★Journal の神大家関連抜粋（Mac sync）
create table if not exists public.glucon_journal_days (
  recorded_at date primary key,
  excerpt text not null default '',
  keywords text[] not null default '{}',
  char_count integer not null default 0,
  synced_at timestamptz not null default now()
);

create index if not exists glucon_journal_days_synced_idx
  on public.glucon_journal_days (synced_at desc);

-- glucon_report_drafts: 活動報告 / 成果報告 下書き
create table if not exists public.glucon_report_drafts (
  id uuid primary key default gen_random_uuid(),
  period_key text not null,
  kind text not null check (kind in ('activity', 'result')),
  glucon_date date,
  report_deadline date,
  title text not null default '',
  body text not null default '',
  status text not null default 'draft'
    check (status in ('draft', 'ready', 'queued', 'posted', 'failed', 'skipped')),
  examples jsonb not null default '[]'::jsonb,
  journal_day_count integer not null default 0,
  post_error text,
  posted_at timestamptz,
  westudy_comment_id text,
  payload jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (period_key, kind)
);

create index if not exists glucon_report_drafts_status_idx
  on public.glucon_report_drafts (status, updated_at desc);

-- glucon_carry_memos: 次月報告に回すメモ（下書き周期とは独立）
create table if not exists public.glucon_carry_memos (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  body text not null default '',
  kind_hint text not null default 'result'
    check (kind_hint in ('result', 'activity', 'either')),
  status text not null default 'open'
    check (status in ('open', 'used', 'discarded')),
  parked_period_key text not null,
  available_from_period_key text not null,
  used_in_period_key text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists glucon_carry_memos_status_idx
  on public.glucon_carry_memos (status, available_from_period_key);

-- RLS: 本人（authenticated）のみ。Service Role はバイパス。
alter table public.triage_items enable row level security;
alter table public.watch_status enable row level security;
alter table public.cards enable row level security;
alter table public.metrics enable row level security;
alter table public.sync_meta enable row level security;
alter table public.subscription_services enable row level security;
alter table public.watch_comments enable row level security;
alter table public.card_comments enable row level security;
alter table public.lane_action_log enable row level security;
alter table public.property_units enable row level security;
alter table public.property_occupancy_events enable row level security;
alter table public.vital_snore_daily enable row level security;
alter table public.vital_treatment_events enable row level security;
alter table public.vital_daily enable row level security;
alter table public.vital_journal_daily enable row level security;
alter table public.vital_context_notes enable row level security;
alter table public.vital_quiet_reviews enable row level security;
alter table public.glucon_schedule enable row level security;
alter table public.glucon_journal_days enable row level security;
alter table public.glucon_report_drafts enable row level security;
alter table public.glucon_carry_memos enable row level security;

-- 単一ユーザー想定: ログイン済みなら全行可。将来 multi-user なら owner_id を追加。
drop policy if exists triage_items_auth_all on public.triage_items;
create policy triage_items_auth_all on public.triage_items
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists watch_status_auth_all on public.watch_status;
create policy watch_status_auth_all on public.watch_status
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists cards_auth_all on public.cards;
create policy cards_auth_all on public.cards
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists metrics_auth_all on public.metrics;
create policy metrics_auth_all on public.metrics
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists sync_meta_auth_all on public.sync_meta;
create policy sync_meta_auth_all on public.sync_meta
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists subscription_services_auth_all on public.subscription_services;
create policy subscription_services_auth_all on public.subscription_services
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists watch_comments_auth_all on public.watch_comments;
create policy watch_comments_auth_all on public.watch_comments
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists card_comments_auth_all on public.card_comments;
create policy card_comments_auth_all on public.card_comments
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists lane_action_log_auth_all on public.lane_action_log;
create policy lane_action_log_auth_all on public.lane_action_log
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists property_units_auth_all on public.property_units;
create policy property_units_auth_all on public.property_units
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists property_occupancy_events_auth_all on public.property_occupancy_events;
create policy property_occupancy_events_auth_all on public.property_occupancy_events
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists vital_snore_daily_auth_all on public.vital_snore_daily;
create policy vital_snore_daily_auth_all on public.vital_snore_daily
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists vital_treatment_events_auth_all on public.vital_treatment_events;
create policy vital_treatment_events_auth_all on public.vital_treatment_events
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists vital_daily_auth_all on public.vital_daily;
create policy vital_daily_auth_all on public.vital_daily
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists vital_journal_daily_auth_all on public.vital_journal_daily;
create policy vital_journal_daily_auth_all on public.vital_journal_daily
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists vital_context_notes_auth_all on public.vital_context_notes;
create policy vital_context_notes_auth_all on public.vital_context_notes
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists vital_quiet_reviews_auth_all on public.vital_quiet_reviews;
create policy vital_quiet_reviews_auth_all on public.vital_quiet_reviews
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists glucon_schedule_auth_all on public.glucon_schedule;
create policy glucon_schedule_auth_all on public.glucon_schedule
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists glucon_journal_days_auth_all on public.glucon_journal_days;
create policy glucon_journal_days_auth_all on public.glucon_journal_days
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists glucon_report_drafts_auth_all on public.glucon_report_drafts;
create policy glucon_report_drafts_auth_all on public.glucon_report_drafts
  for all to authenticated
  using (true)
  with check (true);

drop policy if exists glucon_carry_memos_auth_all on public.glucon_carry_memos;
create policy glucon_carry_memos_auth_all on public.glucon_carry_memos
  for all to authenticated
  using (true)
  with check (true);

-- Trade Desk / 資産全体ビュー: migrations/20260812_trade_desk.sql を正本とする
-- trade_instruments, trade_prices, trade_signals, trade_orders, trade_positions,
-- trade_daily_pnl, trade_risk_state, trade_params, trade_reviews, trade_research,
-- portfolio_accounts, portfolio_snapshots, portfolio_cashflows, advisor_notes
-- KURASHIFT HQ: migrations/20260812_kurashift_hq_liquidity.sql
-- liquidity_accounts, liquidity_snapshots, cashflow_week_summaries,
-- securities_holdings, kurashift_money_ops
-- （kind に card_settlement_buffer を追加: migrations/20260814_kurashift_money_ops_card_settlement.sql）
-- KURASHIFT 時点履歴: migrations/20260813_kurashift_history.sql
-- kurashift_lifeplan_versions, kurashift_lifeplan_budget_rows, kurashift_lifeplan_sheet_dumps,
-- kurashift_finance_sources, kurashift_finance_transactions, kurashift_finance_category_year
-- （migrations/20260813_kurashift_history.sql）
-- kurashift_buy_plan_versions/events/criteria/constraints/notes,
-- kurashift_re_deals, kurashift_ops_consult_events
-- （migrations/20260813_kurashift_buy_plan.sql）
-- 第一問い合わせ箱: inquiry_* 列 / kurashift_re_deal_messages / consultations.lane=realestate
-- （migrations/20260815_kurashift_re_inquiry.sql）
-- job watch / inquiry sending / auto_pass learn / realtime jobs
-- （migrations/20260816_kurashift_job_watch_autopass_learn.sql）
-- kurashift_loan_tracker_loans
-- （migrations/20260813_kurashift_loan_tracker.sql）
-- kurashift_tax_year_metrics（個人暦年／法人5月期の申告結果KPI）
-- （migrations/20260814_kurashift_tax_year_metrics.sql）
-- kurashift_mq_period_facts（MQ会計評価・月次実績／年額F÷12）
-- （migrations/20260816_kurashift_mq_period_facts.sql）
-- kurashift_mq_account_map（Zaim→MQ要素）
-- （migrations/20260816_kurashift_mq_account_map.sql）
-- kurashift_mq_bs_snapshots（軽量B/S・欠損はNULL）
-- （migrations/20260816_kurashift_mq_bs_snapshots.sql）
