login_hint: matsuno.estate@gmail.com
kadai_spreadsheet_id: 1sLFT6HfUBms3R-j3JS13OXCbzVpAL9O3tsF9n8d8kzM
koteihyo_sheet_name: 【工程表】
member_number: '1162'
saiten_spreadsheet_id: 1ZX2xVBpUAtQOB6wz4_CpcZ3lIxhVdtrzS_dGd1yqPkQ
saiten_gas_script_id: 1xpMU8HlELuGGXKTg0Cxmxg8255Wgg5am9C2xHVUZokNnf2xTjyk4li1g
# 採点ツール保存フォルダ（打合せ共有）https://drive.google.com/drive/folders/1QI-r0upkP335FZNQ8q99pe7FpPfTt1h_
saiten_drive_folder_id: 1QI-r0upkP335FZNQ8q99pe7FpPfTt1h_
